In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [2]:
data= pd.read_csv('shipments.csv')

In [3]:
data.head()

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               D           Flight                    4                2   
1   2               F           Flight                    4                5   
2   3               A           Flight                    2                2   
3   4               B           Flight                    3                3   
4   5               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F   
1                  216                2                low      M   
2                  183                4                low      M   
3                  176                4             medium      M   
4                  184                3             medium      F   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
0                44           1233                    1  
1                59           3088                    1  
2                48           3374                    1  
3                10           1177                    1  
4                46           2484                    1

In [4]:
data.drop(["ID"],inplace=True,axis = 1)

In [5]:
data.shape

(10999, 11)

In [6]:
from sklearn import preprocessing
lable_encoder = preprocessing.LabelEncoder()

In [11]:
data['Warehouse_block'] = lable_encoder.fit_transform(data.Warehouse_block)
data['Mode_of_Shipment'] = lable_encoder.fit_transform(data.Mode_of_Shipment)
data['Product_importance'] = lable_encoder.fit_transform(data.Product_importance)
data['Gender'] = lable_encoder.fit_transform(data.Gender)


In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10999 entries, 0 to 10998
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Warehouse_block      10999 non-null  int64
 1   Mode_of_Shipment     10999 non-null  int32
 2   Customer_care_calls  10999 non-null  int64
 3   Customer_rating      10999 non-null  int64
 4   Cost_of_the_Product  10999 non-null  int64
 5   Prior_purchases      10999 non-null  int64
 6   Product_importance   10999 non-null  int32
 7   Gender               10999 non-null  int32
 8   Discount_offered     10999 non-null  int64
 9   Weight_in_gms        10999 non-null  int64
 10  Reached.on.Time_Y.N  10999 non-null  int64
dtypes: int32(3), int64(8)
memory usage: 816.5 KB


In [14]:
array = data.values

In [15]:
X = array[:,0:10]
Y = array[:,10]

In [16]:
X

array([[   3,    0,    4, ...,    0,   44, 1233],
       [   4,    0,    4, ...,    1,   59, 3088],
       [   0,    0,    2, ...,    1,   48, 3374],
       ...,
       [   2,    2,    5, ...,    0,    4, 1155],
       [   4,    2,    5, ...,    1,    2, 1210],
       [   3,    2,    2, ...,    0,    6, 1639]], dtype=int64)

In [17]:
Y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3, random_state= 30)

In [19]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((7699, 10), (3300, 10), (7699,), (3300,))

In [20]:
help(SVC)
model_linear = SVC(kernel = "linear")
model_linear.fit(X_train,Y_train)

Help on class SVC in module sklearn.svm._classes:

class SVC(sklearn.svm._base.BaseSVC)
 |  SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)
 |  
 |  C-Support Vector Classification.
 |  
 |  The implementation is based on libsvm. The fit time scales at least
 |  quadratically with the number of samples and may be impractical
 |  beyond tens of thousands of samples. For large datasets
 |  consider using :class:`sklearn.svm.LinearSVC` or
 |  :class:`sklearn.linear_model.SGDClassifier` instead, possibly after a
 |  :class:`sklearn.kernel_approximation.Nystroem` transformer.
 |  
 |  The multiclass support is handled according to a one-vs-one scheme.
 |  
 |  For details on the precise mathematical formulation of the provided
 |  kernel functions and how `gamma`, `coef0` and `degree` affect each
 |  

SVC(kernel='linear')

In [21]:
from sklearn.datasets import load_svmlight_file
from sklearn import svm

In [22]:
Y_pred = model_linear.predict(X_test)

In [23]:
np.mean(Y_pred==Y_test)

0.6424242424242425

In [24]:
confusion_matrix(Y_test, Y_pred)

array([[1015,  304],
       [ 876, 1105]], dtype=int64)

In [25]:
model_poly = SVC(kernel = "poly")
model_poly.fit(X_train,Y_train)
Y_pred = model_poly.predict(X_test)

In [26]:
np.mean(Y_pred==Y_test)

0.646969696969697

In [27]:
confusion_matrix(Y_test, Y_pred)

array([[ 605,  714],
       [ 451, 1530]], dtype=int64)

In [28]:
model_rbf = SVC(kernel = "rbf")
model_rbf.fit(X_train,Y_train)
Y_pred = model_rbf.predict(X_test)

In [29]:
np.mean(Y_pred==Y_test)

0.6578787878787878

In [30]:
confusion_matrix(Y_test, Y_pred)

array([[ 806,  513],
       [ 616, 1365]], dtype=int64)